### ISSUE TITLE
user cannot delete image of the event he either hosts or participates

### ISSUE THREAD

**Issue by tom-aglow** [tom-aglow/board_buddies#74]

**Comment by tom-aglow** [comment]
@tak4822 who can delete event images?
- only the host?
- only the user who has uploaded the image?
- can the host delete any image then?

**Comment by tak4822** [comment]
I think the only host is able to edit event images (update and delete).
Participants have no ability to make change for any event information and images.
Should they have the ability to upload images?

**Comment by tom-aglow** [comment]
@tak4822 I'm not sure, but why not )) maybe it could be a future feature then, if users ask for that. @darthnish, what do you think?

**Comment by tak4822** [comment]
I agree with that. Now we don’t have group page and all events are based on what game thet are playing. But once app grown upp and some community is created, the feature for participants to upload images are super usefull.
