### ISSUE TITLE
Event location

### ISSUE THREAD

**Issue by tak4822** [tom-aglow/board_buddies#98]
@tom-aglow, @darthnish
When a user creates events, I am trying to post address and coordinates. But I realize it works only when a user chooses their address from autocomplete. But if the events happening in a building, they are not able to type the information. For instance, Vanarts address is 570 Dunsmuir St #600, Vancouver, BC V6B 1Y1 but they can't type '#600'.How do you think guys?

**Comment by tom-aglow** [comment]
@tak4822 is user then able to choose location name? like Vanarts, for example? one possible solution is user can specify suite number in event description.

**Comment by tak4822** [comment]
@tom-aglow 
That's a good one for a public event. How about Private? How do we tell specific address to participants? If we send an email or some notification to tell participants about a specific address, we have to know the specific address?

**Comment by tom-aglow** [comment]
@tak4822, i think it should work the same way. host creates an event and provides building address in the address field plus apartment number in the description. when guest joins the event, he will be able to see exact address of the building and apartment as well. in email we can send all info about the event.

**Comment by tak4822** [comment]
Yeah, I think it will work. We might want to comment somewhere to tell host "write your extra address info in the description". Then I will make like the host has to choose an address in autocomplete. Thanks, Tom!
